name: ChatOps

on:
  issue_comment:
    types: [created]

jobs:
  sonar:
    name: 'SonarCloud on PR'

    runs-on: ubuntu-latest
    if: github.event.comment.body == '/sonar' && (github.event.comment.author_association == 'COLLABORATOR' || github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'MEMBER')

    steps:
      - name: get pull request url
        id: pullrequest
        run: echo "::set-output name=pullrequest::$(curl ${{ github.event.comment.issue_url }} | jq '.pull_request.url' | sed 's/\"//g')"
      - name: get branch name
        id: branchname
        run: echo "::set-output name=branchname::$(curl ${{ steps.pullrequest.outputs.pullrequest }} | jq '.head.ref' | sed 's/\"//g')"
      - name: get repository
        id: repository
        run: echo "::set-output name=repository::$(curl ${{ steps.pullrequest.outputs.pullrequest }} | jq '.head.repo.full_name' | sed 's/\"//g')"
      - run: echo ${PR_BASE} ${PR_HEAD} ${PR_URL/\/cwa-server\/issues\//test} ${{ github.event.comment.body }} ${{ steps.repository.outputs.pullrequest }} ${{ steps.repository.outputs.repository }} ${{ steps.branchname.outputs.branchname }}
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PR_URL:  ${{ github.event.comment.issue_url }}
          PR_BASE:  ${{ github.base_ref }}
          PR_HEAD:  ${{ github.head_ref }}
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          repository: ${{ steps.repository.outputs.repository }}
          ref: ${{ steps.branchname.outputs.branchname }}
      - run: git remote add upstream https://${CHATOPS_USER}:${CHATOPS_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          CHATOPS_TOKEN: ${{ secrets.CHATOPS_TOKEN }}
          CHATOPS_USER: ${{ secrets.CHATOPS_USER }}
      - run: git push -f upstream HEAD:chatops-sonar
