name: "ci"

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    - sonarAction
    - chatops-sonar

jobs:
  sonar:
    runs-on: ubuntu-latest
    if: $GITHUB_REPOSITORY == 'CCFenner/cwa-server'

    name: 'github actions: sonar'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-sonar-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-sonar-
          ${{ runner.os }}-maven-
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: |
        mvn --batch-mode verify sonar:sonar \
        -Dsonar.login=${SONAR_TOKEN} \
        -Dsonar.host.url=${SONAR_URL} \
        -Dsonar.organization=ccfenner \
        -Dsonar.projectKey=${GITHUB_REPOSITORY/\//_}
      env:
        SONAR_URL: https://sonarcloud.io
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
