name: Sonar Analysis

on:
  push:
    branches:
    - master
    - sonar-from-fork
  pull_request:
    branches:
    - master
    - sonar-from-fork

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven Packages
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn --batch-mode --file pom.xml package -DskipTests=true
    - name: Scan with SonarCloud
      run: mvn --batch-mode --file pom.xml sonar:sonar -Dsonar.organization=ccfenner
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
